services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - type: bind
        source: ./
        target: /app
    working_dir: /app
    ports:
      - "8080:8080"